# Generated by Django 2.2.7 on 2019-12-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_auto_20191209_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=50, verbose_name='The Address'),
        ),
    ]
